import { db, API_BASE } from "@/lib/db";

export const IMAGE_EXT = ["jpg", "jpeg", "png", "webp", "gif", "avif", "svg", "heic", "heif", "bmp", "tiff"];
export const VIDEO_EXT = ["mp4", "mov", "webm", "mkv", "avi", "m4v", "ogv", "3gp"];

export function isImage(url: string) {
  const u = url.toLowerCase().split("?")[0];
  return IMAGE_EXT.some((e) => u.endsWith("." + e)) || u.startsWith("data:image/");
}

export function isVideo(url: string) {
  const u = url.toLowerCase().split("?")[0];
  return VIDEO_EXT.some((e) => u.endsWith("." + e));
}

/** Public URL of an uploaded file. Legacy stored URLs are mapped to /uploads. */
export function mediaSrc(url: string | null | undefined): string {
  if (!url) return "";
  const legacyMarkers = ["/storage/v1/object/public/media/", "/api/public/media/"];
  for (const marker of legacyMarkers) {
    const i = url.indexOf(marker);
    if (i !== -1) return "/uploads/" + url.slice(i + marker.length).split("?")[0];
  }
  return url;
}

export const MAX_UPLOAD_BYTES = 50 * 1024 * 1024; // matches api/upload.php

/** Downscaled preview generated by api/thumb.php (originals stay untouched). */
export function mediaThumb(url: string | null | undefined, width = 480): string {
  const src = mediaSrc(url);
  if (!src) return "";
  if (isVideo(src)) return src;
  const i = src.lastIndexOf("/uploads/");
  if (i === -1) return src;
  const file = src.slice(i + "/uploads/".length).split("?")[0];
  return `${API_BASE}/thumb.php?f=${encodeURIComponent(file)}&w=${width}`;
}

function extOf(name: string) {
  return name.toLowerCase().split(".").pop() ?? "";
}

// Some browsers omit the MIME type for .mov / .mkv, so the extension is checked too.
export function acceptedMime(file: File) {
  if (file.type.startsWith("image/") || file.type.startsWith("video/")) return true;
  const ext = extOf(file.name);
  return IMAGE_EXT.includes(ext) || VIDEO_EXT.includes(ext);
}

export async function uploadMedia(file: File): Promise<string> {
  if (!acceptedMime(file)) {
    throw new Error("Unsupported file format. Only images and videos are accepted.");
  }
  if (file.size > MAX_UPLOAD_BYTES) {
    throw new Error(
      `File "${file.name}" is too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Maximum is 50 MB per file — please compress or split the video.`,
    );
  }
  const { url, error } = await db.upload(file);
  if (error || !url) throw new Error(`Failed to upload "${file.name}": ${error?.message ?? "unknown error"}`);
  return url;
}
